services:
  - type: web
    name: avenquis-backend
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run db:migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN_FRONTEND
        sync: false
      - key: CORS_ORIGIN_CONTROL_PANEL
        sync: false
      - key: JWT_SECRET
        sync: false
